### ISSUE TITLE
Dead link: Tutorial video link for visualizing modes using ParaView

### ISSUE THREAD

**Issue by j3soon** [js1019/PlanetaryModels#5]
In `visual/README.md`, there's a recommended tutorial for readers to follow, however, [the link](https://www.youtube.com/watch?v=cygVdhn-kG0) is unavailable... Is there any alternative link?

**Comment by js1019** [comment]
> In `visual/README.md`, there's a recommended tutorial for readers to follow, however, [the link](https://www.youtube.com/watch?v=cygVdhn-kG0) is unavailable... Is there any alternative link?

@j3soon Sorry about that. It was a neat video. I updated [README](https://github.com/js1019/PlanetaryModels/blob/master/visual/README.md). Please let me know if you have questions about the visualization.

**Comment by j3soon** [comment]
@js1019 Thanks for the update! However I'm still struggling to visualize it like the expected outcome in [NormalModes](https://github.com/js1019/NormalModes):

<img src="https://raw.githubusercontent.com/js1019/NormalModes/master/figs/PREM2M_J2_0S2.png" width="400" />

I've tried using the models both in `PlanetaryModels/visual/demos/` and the output of [NormalModes](https://github.com/js1019/NormalModes). (converted to `.vtk` through the MatLab scripts) I've tried Glyphs and Streamlines with/without custom source, but both failed.

I would appreciate if there's some further tips or maybe even re-upload the video?

**Comment by js1019** [comment]
> @js1019 Thanks for the update! However I'm still struggling to visualize it like the expected outcome in [NormalModes](https://github.com/js1019/NormalModes):
> 
> <img alt="" width="400" src="https://raw.githubusercontent.com/js1019/NormalModes/master/figs/PREM2M_J2_0S2.png">
> 
> I've tried using the models both in `PlanetaryModels/visual/demos/` and the output of [NormalModes](https://github.com/js1019/NormalModes). (converted to `.vtk` through the MatLab scripts) I've tried Glyphs and Streamlines with/without custom source, but both failed.
> 
> I would appreciate if there's some further tips or maybe even re-upload the video?

@j3soon  Are there any error messages? I simply use Glyph. If you can see clear patterns, that should be enough. Sadly, I can't find a similar video.

**Comment by j3soon** [comment]
@js1019 There are no error messages. I can see clear patterns but are not exactly the same as the expected outcome. They're quite similar, though.

![image](https://user-images.githubusercontent.com/20457146/62839803-71c62880-bcc2-11e9-8d9b-306f23576f85.png)

**Comment by js1019** [comment]
@j3soon It looks correct. The sizes of the arrows are quite large. You may play with the scaling factor to resize the arrows and the number of points needed.

**Comment by j3soon** [comment]
okay! Thanks a lot!

**Comment by j3soon** [comment]
@js1019 After fixing the size of the arrows and played with the option: `Maximum Number Of Sample Points`. I still have 3 questions about visualizing:
1. The arrows still seems sparse comparing to the visualization example, regardless the high value and different settings of `Maximum Number Of Sample Points`.

   <img src="https://user-images.githubusercontent.com/20457146/63448502-9a8fb000-c470-11e9-85d1-c7dcdeefe19b.png" width="400" />

2. The visual I created seems to belong to spheroidal mode, how can I calculate toroidal modes?
3. There is 1 extra sphere inside the toroidal modes, 2 extra spheres inside the spheroidal modes. Can you elaborate more on this?

![](https://user-images.githubusercontent.com/20457146/63449274-5b625e80-c472-11e9-83f3-2081d166ff7f.png)

**Comment by js1019** [comment]
> @js1019 After fixing the size of the arrows and played with the option: `Maximum Number Of Sample Points`. I still have 3 questions about visualizing:
> 
> 1. The arrows still seems sparse comparing to the visualization example, regardless the high value and different settings of `Maximum Number Of Sample Points`.
>    <img alt="" width="400" src="https://user-images.githubusercontent.com/20457146/63448502-9a8fb000-c470-11e9-85d1-c7dcdeefe19b.png">

Please check the total number of vertices of your current model. Once you obtain results from a large-scale problem, you will see the differences. 

> 2. The visual I created seems to belong to spheroidal mode, how can I calculate toroidal modes?

Please check and visualize other computed modes. You will see toroidal modes as well. 

> 3. There is 1 extra sphere inside the toroidal modes, 2 extra spheres inside the spheroidal modes. Can you elaborate more on this?
> 
> ![](https://user-images.githubusercontent.com/20457146/63449274-5b625e80-c472-11e9-83f3-2081d166ff7f.png)

Here is a sample script to create multiple interfaces: https://github.com/js1019/PlanetaryModels/blob/master/Demos/GravityETC/plot_interfaces.m 

Please let me know if you have more questions.

**Comment by j3soon** [comment]
Thanks, I'll try them out!

**Comment by j3soon** [comment]
@js1019 I still have trouble creating multiple interfaces, [the script](https://github.com/js1019/PlanetaryModels/blob/master/Demos/GravityETC/plot_interfaces.m) you linked above seems to generate only a single sphere. 

<img src="https://user-images.githubusercontent.com/20457146/63710314-7f0b1780-c86b-11e9-80fd-3b74b6848e2b.png" width="300" />

After some searching, I can only find the code snippet below that seems to create multiple interfaces (but actually doesn't):

https://github.com/js1019/PlanetaryModels/blob/a9b567e4e44bffe1daa129abfa84f0bfe364b909/Demos/PREM/PREM_mesh.m#L38-L48

I think I might overlook some details, can you explain more about creating multiple interfaces?

**Comment by js1019** [comment]
I am not sure if I understand your questions correctly. To visualize multi-faces, you can simply add several single interfaces together.

**Comment by j3soon** [comment]
Oh, I think I overthought the meaning of the multi-faces... So the inner spheres are only used for indicating the size of the outer / inner core? (for better visualization?)

So, to decide whether showing both cores or only the outer core:
- For toroidal modes, only the outer core are shown, since all normal modes should lie outside the outer core (in the Earth's mantle).
- For spheroidal modes, both cores are shown since the normal modes might originate within the inner core.

Is my interpretation above correct?

**Comment by js1019** [comment]
> Oh, I think I overthought the meaning of the multi-faces... So the inner spheres are only used for indicating the size of the outer / inner core? (for better visualization?)

This is correct. 

> 
> So, to decide whether showing both cores or only the outer core:
> 
> * For toroidal modes, only the outer core are shown, since all normal modes should lie outside the outer core (in the Earth's mantle).
> * For spheroidal modes, both cores are shown since the normal modes might originate within the inner core.
> 
> Is my interpretation above correct? 

This is correct for simple models (spherically symmetric, or close to spherically symmetric). For a general model, it is not also the case. The patterns could be quite complicated.

**Comment by j3soon** [comment]
Got it! I have another question:
In the figure, each visualized normal modes has its subscription `n` and `l`, which is the overtone number and the spherical-harmonic number respectively.
The output of the calculated normal modes are labeled as the `nth` normal mode. Are there any way to map the `nth` mode to `n` and `l` in the figure?

![](https://user-images.githubusercontent.com/20457146/63449274-5b625e80-c472-11e9-83f3-2081d166ff7f.png)

**Comment by js1019** [comment]
> Got it! I have another question:
> In the figure, each visualized normal modes has its subscription `n` and `l`, which is the overtone number and the spherical-harmonic number respectively.
> The output of the calculated normal modes are labeled as the `nth` normal mode. Are there any way to map the `nth` mode to `n` and `l` in the figure?
> 
> ![](https://user-images.githubusercontent.com/20457146/63449274-5b625e80-c472-11e9-83f3-2081d166ff7f.png)

There are rules to determine n and l but it will be better to use a radial solution. The spherical harmonic decomposition works well for spherically symmetrical problems. However, I don't think it is required for computer scientists. In addition, for the general cases, there are no clear n and l.

**Comment by j3soon** [comment]
okay! Thank you very much!
